# This is a basic workflow to help you get started with Actions

name: Publish NuGet

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    name: build, pack & publish
    runs-on: windows-latest
    if: |
      contains(github.event.head_commit.message, '#pack')
    steps:
      - uses: actions/checkout@v2
      - name: Setup MSBuild Path
        uses: microsoft/setup-msbuild@v1.1
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      - name: Get Version of MultiComboBox
        uses: naminodarie/get-net-sdk-project-versions-action@v1
        id: get-version
        with:
          proj-path: MultiComboBox.csproj
      - name: Restore NuGet Packages
        run: nuget restore MultiComboBox.sln
      - name: Build
        run: msbuild MultiComboBox.sln /p:Configuration=Release /p:DeployOnBuild=true
      - name: Push
        run: dotnet nuget push bin/Release/MultiComboBox.${{steps.get-version.outputs.version}}.nupkg --skip-duplicate --source https://nuget.pkg.github.com/pbj-gmbh/index.json --api-key ${{secrets.NUGET_API_KEY}}
